# Generated by Django 5.2.8 on 2025-12-16 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagereceipt',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PurchaseReceipt',
        ),
    ]
