# Generated by Django 5.2.8 on 2025-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_usagereceipt_created_at_delete_purchasereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
