# Generated by Django 5.2.8 on 2025-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_purchasereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
