# Generated by Django 5.2.8 on 2025-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_purchasereceipt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usagereceipt',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
