# Generated by Django 5.2.8 on 2025-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='house',
            field=models.CharField(blank=True, choices=[('gryffindor', 'Gryffindor'), ('hufflepuff', 'Hufflepuff'), ('ravenclaw', 'Ravenclaw'), ('slytherin', 'Slytherin')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('banker', 'Banquero'), ('seller', 'Vendedor')], default='student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
