# Generated by Django 5.2.8 on 2025-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_house_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('banker', 'Banquero'), ('shopkeeper', 'Vendedor')], default='student'),
        ),
    ]
