# Generated by Django 5.2.8 on 2025-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('banker', 'Banquero'), ('shopkeeper', 'Dependiente')], default='student'),
        ),
    ]
