# Generated by Django 5.2.8 on 2026-04-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'product',
            name = 'product_type',
            field = models.CharField(max_length=20, choices=[
                    ('broom', 'Escoba'),
                    ('pet', 'Mascota'),
                    ('wand', 'Varita'),
                    ('wheezes', 'Sortilegios'),
                    ('misc', 'Miscelaneos')
                ], default='misc',
            ),
        ),
    ]