# Generated by Django 5.2.8 on 2025-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_product_discount_alter_inventoryitem_pur_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
