# Generated by Django 5.2.8 on 2026-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
