# Generated by Django 5.2.8 on 2026-04-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
