# Generated by Django 5.2.8 on 2025-12-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
    ]
