# Generated by Django 5.2.8 on 2025-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('broom', 'Escoba'), ('pet', 'Mascota'), ('wand', 'Varita'), ('misc', 'Miscelaneos')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
