# Generated by Django 5.2.8 on 2026-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_remove_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="duration_days",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
