# Generated by Django 5.2.8 on 2025-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('broom', 'Escobas'), ('pet', 'Mascotas'), ('wand', 'Varitas'), ('misc', 'Miscelaneos')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
