# Generated by Django 5.2.8 on 2025-12-14 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ex_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('broom', 'Escoba'), ('pet', 'Mascota'), ('wand', 'Varita'), ('wheezes', 'Sortilegios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_product', to='stores.product'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_store', to='stores.store'),
        ),
    ]
