# Generated by Django 5.2.8 on 2025-12-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_inventoryitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('broom', 'Escobas'), ('pet', 'Mascotas'), ('wand', 'Varitas'), ('wheezes', 'Sortilegios')], max_length=20),
        ),
    ]
