# Generated by Django 5.2.8 on 2026-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_store_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('broom', 'Escoba'), ('pet', 'Mascota'), ('wand', 'Varita'), ('wheezes', 'Sortilegios'), ('misc', 'Miscelaneos')], max_length=20),
        ),
    ]
