# Generated by Django 5.2.8 on 2026-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_store_store_type_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('broom', 'Escoba'), ('pet', 'Mascota'), ('wand', 'Varita'), ('wheezes', 'Sortilegios'), ('misc', 'Miscelaneos')], default='misc', max_length=20),
        ),
    ]
