# Generated by Django 5.2.8 on 2025-12-12 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bank_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_pro', 'Premium Pro')], default='standard')),
                ('created_at', models.DateField(auto_now=True)),
                ('upgraded_at', models.DateField(blank=True, null=True)),
                ('weekly_transactions_left', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.IntegerField(choices=[(0, '25 → 30'), (1, '50 → 60'), (2, '100 → 120')])),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_due', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'paid')], default=0)),
                ('codebtor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_a', to=settings.AUTH_USER_MODEL)),
                ('codebtor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_b', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
