# Generated by Django 5.2.8 on 2025-11-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('is_frozen', models.BooleanField(blank=True, default=False, null=True)),
                ('account_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_pro', 'Premium Pro')], default='standard', max_length=20)),
                ('limit', models.PositiveIntegerField(default=200)),
                ('premium_start_date', models.DateField(blank=True, null=True)),
                ('daily_transaction_limit', models.PositiveIntegerField(default=1)),
                ('daily_received_limit', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.IntegerField(choices=[(0, '25 galeones → 30 galeones'), (1, '50 galeones → 60 galeones'), (2, '100 galeones → 120 galeones')])),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_due', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('codebtor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_a', to=settings.AUTH_USER_MODEL)),
                ('codebtor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_b', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
