# Generated by Django 4.2.30 on 2026-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="zi",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
