# Generated by Django 5.2 on 2025-10-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_start_date',
        ),
    ]
