# Generated by Django 5.2.8 on 2025-12-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='premium_start_date',
            new_name='upgraded_at',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='limit',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_pro', 'Premium Pro')], default='standard'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
