# Generated by Django 5.2.8 on 2025-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_loan_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10),
        ),
    ]
