# Generated by Django 4.2.30 on 2026-08-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_bankaccount_zi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="zi",
        ),
    ]
