# Generated by Django 5.2.8 on 2025-12-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_premium_start_date_bankaccount_upgraded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='daily_received_limit',
            new_name='weekly_transactions_left',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='daily_transaction_limit',
        ),
    ]
