# Generated by Django 5.2 on 2025-10-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_bankaccount_account_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
