# Generated by Django 5.2.8 on 2025-12-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_daily_received_limit_bankaccount_weekly_transactions_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
