# Generated by Django 5.2 on 2025-10-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount_account_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_start_date',
            new_name='premium_start_date',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='premium_ex_date',
        ),
    ]
