# Generated by Django 5.2.8 on 2025-12-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_loan_created_at_loan_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
