# Generated by Django 5.2 on 2025-10-19 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_rename_account_start_date_bankaccount_premium_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.IntegerField(choices=[(0, '25 galeones → 30 galeones'), (1, '50 galeones → 60 galeones'), (2, '100 galeones → 120 galeones')])),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_due', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('codebtor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_a', to=settings.AUTH_USER_MODEL)),
                ('codebtor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_codebtor_b', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
