# Generated by Django 5.2.8 on 2025-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bankaccount_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='frozen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_pur_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_trans_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
