# Generated by Django 5.2.8 on 2025-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_loan_paid_date_alter_loan_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='last_pur_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
